version: '2'
services:
  tycabrisapplication-app:
    image: tycabrisapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://tycabrisapplication-mariadb:3306/tycabrisapplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8082:8082
  tycabrisapplication-mariadb:
    extends:
      file: mariadb.yml
      service: tycabrisapplication-mariadb
